test_that("read_jobactive returns expected output", {
  ja <- read_jobactive()
  expect_s3_class(ja, "tbl_df")
  expect_length(ja, 9)

  expected_names <- c(
    "date",
    "value",
    "series",
    "series_id",
    "series_type",
    "data_type",
    "table_no",
    "frequency",
    "unit"
  )

  expect_true(all(expected_names %in% names(ja)))

  expect_gte(nrow(ja), 8305)

  expect_equal(
    unique(ja$series),
    c(
      "Jobactive caseload ; Total ; Total",
      "Jobactive caseload ; Total ; Adelaide North",
      "Jobactive caseload ; Total ; Adelaide South",
      "Jobactive caseload ; Total ; Ballarat",
      "Jobactive caseload ; Total ; Barwon",
      "Jobactive caseload ; Total ; Bendigo",
      "Jobactive caseload ; Total ; Brisbane South East",
      "Jobactive caseload ; Total ; Broome",
      "Jobactive caseload ; Total ; Cairns",
      "Jobactive caseload ; Total ; Capital Region",
      "Jobactive caseload ; Total ; Central West",
      "Jobactive caseload ; Total ; Darling Downs",
      "Jobactive caseload ; Total ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; Total ; Esperance",
      "Jobactive caseload ; Total ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; Total ; Fitzroy",
      "Jobactive caseload ; Total ; Geraldton",
      "Jobactive caseload ; Total ; Gippsland",
      "Jobactive caseload ; Total ; Gold Coast",
      "Jobactive caseload ; Total ; Goulburn/Murray",
      "Jobactive caseload ; Total ; Great Southern - Wheatbelt",
      "Jobactive caseload ; Total ; Hobart and Southern Tasmania",
      "Jobactive caseload ; Total ; Hunter",
      "Jobactive caseload ; Total ; Illawarra South Coast",
      "Jobactive caseload ; Total ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; Total ; Kalgoorlie",
      "Jobactive caseload ; Total ; Mackay",
      "Jobactive caseload ; Total ; Mid North Coast",
      "Jobactive caseload ; Total ; Mid North SA",
      "Jobactive caseload ; Total ; Murray and South East",
      "Jobactive caseload ; Total ; Murray Riverina",
      "Jobactive caseload ; Total ; New England and North West",
      "Jobactive caseload ; Total ; Norfolk Island",
      "Jobactive caseload ; Total ; North and North Western Tasmania",
      "Jobactive caseload ; Total ; North Coast",
      "Jobactive caseload ; Total ; North Eastern Melbourne",
      "Jobactive caseload ; Total ; North West Country SA",
      "Jobactive caseload ; Total ; North Western Melbourne",
      "Jobactive caseload ; Total ; Perth - North",
      "Jobactive caseload ; Total ; Perth - South",
      "Jobactive caseload ; Total ; Somerset",
      "Jobactive caseload ; Total ; South Coast of Victoria",
      "Jobactive caseload ; Total ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; Total ; South West WA",
      "Jobactive caseload ; Total ; Sydney East Metro",
      "Jobactive caseload ; Total ; Sydney Greater West",
      "Jobactive caseload ; Total ; Sydney North and West",
      "Jobactive caseload ; Total ; Sydney South West",
      "Jobactive caseload ; Total ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; Total ; Western Melbourne",
      "Jobactive caseload ; Total ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; Total ; Wimmera Mallee",
      "Jobactive caseload ; Total ; Wivenhoe",
      "Jobactive caseload ; Total ; Online Employment Services Trial",
      "Jobactive caseload ; Total ; Employment Region Unknown",
      "Jobactive caseload ; Youth (15-24) ; Total",
      "Jobactive caseload ; Youth (15-24) ; Adelaide North",
      "Jobactive caseload ; Youth (15-24) ; Adelaide South",
      "Jobactive caseload ; Youth (15-24) ; Ballarat",
      "Jobactive caseload ; Youth (15-24) ; Barwon",
      "Jobactive caseload ; Youth (15-24) ; Bendigo",
      "Jobactive caseload ; Youth (15-24) ; Brisbane South East",
      "Jobactive caseload ; Youth (15-24) ; Broome",
      "Jobactive caseload ; Youth (15-24) ; Cairns",
      "Jobactive caseload ; Youth (15-24) ; Capital Region",
      "Jobactive caseload ; Youth (15-24) ; Central West",
      "Jobactive caseload ; Youth (15-24) ; Darling Downs",
      "Jobactive caseload ; Youth (15-24) ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; Youth (15-24) ; Esperance",
      "Jobactive caseload ; Youth (15-24) ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; Youth (15-24) ; Fitzroy",
      "Jobactive caseload ; Youth (15-24) ; Geraldton",
      "Jobactive caseload ; Youth (15-24) ; Gippsland",
      "Jobactive caseload ; Youth (15-24) ; Gold Coast",
      "Jobactive caseload ; Youth (15-24) ; Goulburn/Murray",
      "Jobactive caseload ; Youth (15-24) ; Great Southern - Wheatbelt",
      "Jobactive caseload ; Youth (15-24) ; Hobart and Southern Tasmania",
      "Jobactive caseload ; Youth (15-24) ; Hunter",
      "Jobactive caseload ; Youth (15-24) ; Illawarra South Coast",
      "Jobactive caseload ; Youth (15-24) ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; Youth (15-24) ; Kalgoorlie",
      "Jobactive caseload ; Youth (15-24) ; Mackay",
      "Jobactive caseload ; Youth (15-24) ; Mid North Coast",
      "Jobactive caseload ; Youth (15-24) ; Mid North SA",
      "Jobactive caseload ; Youth (15-24) ; Murray and South East",
      "Jobactive caseload ; Youth (15-24) ; Murray Riverina",
      "Jobactive caseload ; Youth (15-24) ; New England and North West",
      "Jobactive caseload ; Youth (15-24) ; Norfolk Island",
      "Jobactive caseload ; Youth (15-24) ; North and North Western Tasmania",
      "Jobactive caseload ; Youth (15-24) ; North Coast",
      "Jobactive caseload ; Youth (15-24) ; North Eastern Melbourne",
      "Jobactive caseload ; Youth (15-24) ; North West Country SA",
      "Jobactive caseload ; Youth (15-24) ; North Western Melbourne",
      "Jobactive caseload ; Youth (15-24) ; Perth - North",
      "Jobactive caseload ; Youth (15-24) ; Perth - South",
      "Jobactive caseload ; Youth (15-24) ; Somerset",
      "Jobactive caseload ; Youth (15-24) ; South Coast of Victoria",
      "Jobactive caseload ; Youth (15-24) ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; Youth (15-24) ; South West WA",
      "Jobactive caseload ; Youth (15-24) ; Sydney East Metro",
      "Jobactive caseload ; Youth (15-24) ; Sydney Greater West",
      "Jobactive caseload ; Youth (15-24) ; Sydney North and West",
      "Jobactive caseload ; Youth (15-24) ; Sydney South West",
      "Jobactive caseload ; Youth (15-24) ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; Youth (15-24) ; Western Melbourne",
      "Jobactive caseload ; Youth (15-24) ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; Youth (15-24) ; Wimmera Mallee",
      "Jobactive caseload ; Youth (15-24) ; Wivenhoe",
      "Jobactive caseload ; Youth (15-24) ; Online Employment Services Trial",
      "Jobactive caseload ; Youth (15-24) ; Employment Region Unknown",
      "Jobactive caseload ; Mature Age (50+) ; Total",
      "Jobactive caseload ; Mature Age (50+) ; Adelaide North",
      "Jobactive caseload ; Mature Age (50+) ; Adelaide South",
      "Jobactive caseload ; Mature Age (50+) ; Ballarat",
      "Jobactive caseload ; Mature Age (50+) ; Barwon",
      "Jobactive caseload ; Mature Age (50+) ; Bendigo",
      "Jobactive caseload ; Mature Age (50+) ; Brisbane South East",
      "Jobactive caseload ; Mature Age (50+) ; Broome",
      "Jobactive caseload ; Mature Age (50+) ; Cairns",
      "Jobactive caseload ; Mature Age (50+) ; Capital Region",
      "Jobactive caseload ; Mature Age (50+) ; Central West",
      "Jobactive caseload ; Mature Age (50+) ; Darling Downs",
      "Jobactive caseload ; Mature Age (50+) ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; Mature Age (50+) ; Esperance",
      "Jobactive caseload ; Mature Age (50+) ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; Mature Age (50+) ; Fitzroy",
      "Jobactive caseload ; Mature Age (50+) ; Geraldton",
      "Jobactive caseload ; Mature Age (50+) ; Gippsland",
      "Jobactive caseload ; Mature Age (50+) ; Gold Coast",
      "Jobactive caseload ; Mature Age (50+) ; Goulburn/Murray",
      "Jobactive caseload ; Mature Age (50+) ; Great Southern - Wheatbelt",
      "Jobactive caseload ; Mature Age (50+) ; Hobart and Southern Tasmania",
      "Jobactive caseload ; Mature Age (50+) ; Hunter",
      "Jobactive caseload ; Mature Age (50+) ; Illawarra South Coast",
      "Jobactive caseload ; Mature Age (50+) ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; Mature Age (50+) ; Kalgoorlie",
      "Jobactive caseload ; Mature Age (50+) ; Mackay",
      "Jobactive caseload ; Mature Age (50+) ; Mid North Coast",
      "Jobactive caseload ; Mature Age (50+) ; Mid North SA",
      "Jobactive caseload ; Mature Age (50+) ; Murray and South East",
      "Jobactive caseload ; Mature Age (50+) ; Murray Riverina",
      "Jobactive caseload ; Mature Age (50+) ; New England and North West",
      "Jobactive caseload ; Mature Age (50+) ; Norfolk Island",
      "Jobactive caseload ; Mature Age (50+) ; North and North Western Tasmania",
      "Jobactive caseload ; Mature Age (50+) ; North Coast",
      "Jobactive caseload ; Mature Age (50+) ; North Eastern Melbourne",
      "Jobactive caseload ; Mature Age (50+) ; North West Country SA",
      "Jobactive caseload ; Mature Age (50+) ; North Western Melbourne",
      "Jobactive caseload ; Mature Age (50+) ; Perth - North",
      "Jobactive caseload ; Mature Age (50+) ; Perth - South",
      "Jobactive caseload ; Mature Age (50+) ; Somerset",
      "Jobactive caseload ; Mature Age (50+) ; South Coast of Victoria",
      "Jobactive caseload ; Mature Age (50+) ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; Mature Age (50+) ; South West WA",
      "Jobactive caseload ; Mature Age (50+) ; Sydney East Metro",
      "Jobactive caseload ; Mature Age (50+) ; Sydney Greater West",
      "Jobactive caseload ; Mature Age (50+) ; Sydney North and West",
      "Jobactive caseload ; Mature Age (50+) ; Sydney South West",
      "Jobactive caseload ; Mature Age (50+) ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; Mature Age (50+) ; Western Melbourne",
      "Jobactive caseload ; Mature Age (50+) ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; Mature Age (50+) ; Wimmera Mallee",
      "Jobactive caseload ; Mature Age (50+) ; Wivenhoe",
      "Jobactive caseload ; Mature Age (50+) ; Online Employment Services Trial",
      "Jobactive caseload ; Mature Age (50+) ; Employment Region Unknown",
      "Jobactive caseload ; Indigenous ; Total",
      "Jobactive caseload ; Indigenous ; Adelaide North",
      "Jobactive caseload ; Indigenous ; Adelaide South",
      "Jobactive caseload ; Indigenous ; Ballarat",
      "Jobactive caseload ; Indigenous ; Barwon",
      "Jobactive caseload ; Indigenous ; Bendigo",
      "Jobactive caseload ; Indigenous ; Brisbane South East",
      "Jobactive caseload ; Indigenous ; Broome",
      "Jobactive caseload ; Indigenous ; Cairns",
      "Jobactive caseload ; Indigenous ; Capital Region",
      "Jobactive caseload ; Indigenous ; Central West",
      "Jobactive caseload ; Indigenous ; Darling Downs",
      "Jobactive caseload ; Indigenous ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; Indigenous ; Esperance",
      "Jobactive caseload ; Indigenous ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; Indigenous ; Fitzroy",
      "Jobactive caseload ; Indigenous ; Geraldton",
      "Jobactive caseload ; Indigenous ; Gippsland",
      "Jobactive caseload ; Indigenous ; Gold Coast",
      "Jobactive caseload ; Indigenous ; Goulburn/Murray",
      "Jobactive caseload ; Indigenous ; Great Southern - Wheatbelt",
      "Jobactive caseload ; Indigenous ; Hobart and Southern Tasmania",
      "Jobactive caseload ; Indigenous ; Hunter",
      "Jobactive caseload ; Indigenous ; Illawarra South Coast",
      "Jobactive caseload ; Indigenous ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; Indigenous ; Kalgoorlie",
      "Jobactive caseload ; Indigenous ; Mackay",
      "Jobactive caseload ; Indigenous ; Mid North Coast",
      "Jobactive caseload ; Indigenous ; Mid North SA",
      "Jobactive caseload ; Indigenous ; Murray and South East",
      "Jobactive caseload ; Indigenous ; Murray Riverina",
      "Jobactive caseload ; Indigenous ; New England and North West",
      "Jobactive caseload ; Indigenous ; Norfolk Island",
      "Jobactive caseload ; Indigenous ; North and North Western Tasmania",
      "Jobactive caseload ; Indigenous ; North Coast",
      "Jobactive caseload ; Indigenous ; North Eastern Melbourne",
      "Jobactive caseload ; Indigenous ; North West Country SA",
      "Jobactive caseload ; Indigenous ; North Western Melbourne",
      "Jobactive caseload ; Indigenous ; Perth - North",
      "Jobactive caseload ; Indigenous ; Perth - South",
      "Jobactive caseload ; Indigenous ; Somerset",
      "Jobactive caseload ; Indigenous ; South Coast of Victoria",
      "Jobactive caseload ; Indigenous ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; Indigenous ; South West WA",
      "Jobactive caseload ; Indigenous ; Sydney East Metro",
      "Jobactive caseload ; Indigenous ; Sydney Greater West",
      "Jobactive caseload ; Indigenous ; Sydney North and West",
      "Jobactive caseload ; Indigenous ; Sydney South West",
      "Jobactive caseload ; Indigenous ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; Indigenous ; Western Melbourne",
      "Jobactive caseload ; Indigenous ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; Indigenous ; Wimmera Mallee",
      "Jobactive caseload ; Indigenous ; Wivenhoe",
      "Jobactive caseload ; Indigenous ; Online Employment Services Trial",
      "Jobactive caseload ; Indigenous ; Employment Region Unknown",
      "Jobactive caseload ; Female ; Total",
      "Jobactive caseload ; Female ; Adelaide North",
      "Jobactive caseload ; Female ; Adelaide South",
      "Jobactive caseload ; Female ; Ballarat",
      "Jobactive caseload ; Female ; Barwon",
      "Jobactive caseload ; Female ; Bendigo",
      "Jobactive caseload ; Female ; Brisbane South East",
      "Jobactive caseload ; Female ; Broome",
      "Jobactive caseload ; Female ; Cairns",
      "Jobactive caseload ; Female ; Capital Region",
      "Jobactive caseload ; Female ; Central West",
      "Jobactive caseload ; Female ; Darling Downs",
      "Jobactive caseload ; Female ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; Female ; Esperance",
      "Jobactive caseload ; Female ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; Female ; Fitzroy",
      "Jobactive caseload ; Female ; Geraldton",
      "Jobactive caseload ; Female ; Gippsland",
      "Jobactive caseload ; Female ; Gold Coast",
      "Jobactive caseload ; Female ; Goulburn/Murray",
      "Jobactive caseload ; Female ; Great Southern - Wheatbelt",
      "Jobactive caseload ; Female ; Hobart and Southern Tasmania",
      "Jobactive caseload ; Female ; Hunter",
      "Jobactive caseload ; Female ; Illawarra South Coast",
      "Jobactive caseload ; Female ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; Female ; Kalgoorlie",
      "Jobactive caseload ; Female ; Mackay",
      "Jobactive caseload ; Female ; Mid North Coast",
      "Jobactive caseload ; Female ; Mid North SA",
      "Jobactive caseload ; Female ; Murray and South East",
      "Jobactive caseload ; Female ; Murray Riverina",
      "Jobactive caseload ; Female ; New England and North West",
      "Jobactive caseload ; Female ; Norfolk Island",
      "Jobactive caseload ; Female ; North and North Western Tasmania",
      "Jobactive caseload ; Female ; North Coast",
      "Jobactive caseload ; Female ; North Eastern Melbourne",
      "Jobactive caseload ; Female ; North West Country SA",
      "Jobactive caseload ; Female ; North Western Melbourne",
      "Jobactive caseload ; Female ; Perth - North",
      "Jobactive caseload ; Female ; Perth - South",
      "Jobactive caseload ; Female ; Somerset",
      "Jobactive caseload ; Female ; South Coast of Victoria",
      "Jobactive caseload ; Female ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; Female ; South West WA",
      "Jobactive caseload ; Female ; Sydney East Metro",
      "Jobactive caseload ; Female ; Sydney Greater West",
      "Jobactive caseload ; Female ; Sydney North and West",
      "Jobactive caseload ; Female ; Sydney South West",
      "Jobactive caseload ; Female ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; Female ; Western Melbourne",
      "Jobactive caseload ; Female ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; Female ; Wimmera Mallee",
      "Jobactive caseload ; Female ; Wivenhoe",
      "Jobactive caseload ; Female ; Online Employment Services Trial",
      "Jobactive caseload ; Female ; Employment Region Unknown",
      "Jobactive caseload ; PWD ; Total",
      "Jobactive caseload ; PWD ; Adelaide North",
      "Jobactive caseload ; PWD ; Adelaide South",
      "Jobactive caseload ; PWD ; Ballarat",
      "Jobactive caseload ; PWD ; Barwon",
      "Jobactive caseload ; PWD ; Bendigo",
      "Jobactive caseload ; PWD ; Brisbane South East",
      "Jobactive caseload ; PWD ; Broome",
      "Jobactive caseload ; PWD ; Cairns",
      "Jobactive caseload ; PWD ; Capital Region",
      "Jobactive caseload ; PWD ; Central West",
      "Jobactive caseload ; PWD ; Darling Downs",
      "Jobactive caseload ; PWD ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; PWD ; Esperance",
      "Jobactive caseload ; PWD ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; PWD ; Fitzroy",
      "Jobactive caseload ; PWD ; Geraldton",
      "Jobactive caseload ; PWD ; Gippsland",
      "Jobactive caseload ; PWD ; Gold Coast",
      "Jobactive caseload ; PWD ; Goulburn/Murray",
      "Jobactive caseload ; PWD ; Great Southern - Wheatbelt",
      "Jobactive caseload ; PWD ; Hobart and Southern Tasmania",
      "Jobactive caseload ; PWD ; Hunter",
      "Jobactive caseload ; PWD ; Illawarra South Coast",
      "Jobactive caseload ; PWD ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; PWD ; Kalgoorlie",
      "Jobactive caseload ; PWD ; Mackay",
      "Jobactive caseload ; PWD ; Mid North Coast",
      "Jobactive caseload ; PWD ; Mid North SA",
      "Jobactive caseload ; PWD ; Murray and South East",
      "Jobactive caseload ; PWD ; Murray Riverina",
      "Jobactive caseload ; PWD ; New England and North West",
      "Jobactive caseload ; PWD ; Norfolk Island",
      "Jobactive caseload ; PWD ; North and North Western Tasmania",
      "Jobactive caseload ; PWD ; North Coast",
      "Jobactive caseload ; PWD ; North Eastern Melbourne",
      "Jobactive caseload ; PWD ; North West Country SA",
      "Jobactive caseload ; PWD ; North Western Melbourne",
      "Jobactive caseload ; PWD ; Perth - North",
      "Jobactive caseload ; PWD ; Perth - South",
      "Jobactive caseload ; PWD ; Somerset",
      "Jobactive caseload ; PWD ; South Coast of Victoria",
      "Jobactive caseload ; PWD ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; PWD ; South West WA",
      "Jobactive caseload ; PWD ; Sydney East Metro",
      "Jobactive caseload ; PWD ; Sydney Greater West",
      "Jobactive caseload ; PWD ; Sydney North and West",
      "Jobactive caseload ; PWD ; Sydney South West",
      "Jobactive caseload ; PWD ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; PWD ; Western Melbourne",
      "Jobactive caseload ; PWD ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; PWD ; Wimmera Mallee",
      "Jobactive caseload ; PWD ; Wivenhoe",
      "Jobactive caseload ; PWD ; Online Employment Services Trial",
      "Jobactive caseload ; PWD ; Employment Region Unknown",
      "Jobactive caseload ; Refugee ; Total",
      "Jobactive caseload ; Refugee ; Adelaide North",
      "Jobactive caseload ; Refugee ; Adelaide South",
      "Jobactive caseload ; Refugee ; Ballarat",
      "Jobactive caseload ; Refugee ; Barwon",
      "Jobactive caseload ; Refugee ; Bendigo",
      "Jobactive caseload ; Refugee ; Brisbane South East",
      "Jobactive caseload ; Refugee ; Broome",
      "Jobactive caseload ; Refugee ; Cairns",
      "Jobactive caseload ; Refugee ; Capital Region",
      "Jobactive caseload ; Refugee ; Central West",
      "Jobactive caseload ; Refugee ; Darling Downs",
      "Jobactive caseload ; Refugee ; Darwin (includes Alice Springs)",
      "Jobactive caseload ; Refugee ; Esperance",
      "Jobactive caseload ; Refugee ; Far West Orana (includes Broken Hill)",
      "Jobactive caseload ; Refugee ; Fitzroy",
      "Jobactive caseload ; Refugee ; Geraldton",
      "Jobactive caseload ; Refugee ; Gippsland",
      "Jobactive caseload ; Refugee ; Gold Coast",
      "Jobactive caseload ; Refugee ; Goulburn/Murray",
      "Jobactive caseload ; Refugee ; Great Southern - Wheatbelt",
      "Jobactive caseload ; Refugee ; Hobart and Southern Tasmania",
      "Jobactive caseload ; Refugee ; Hunter",
      "Jobactive caseload ; Refugee ; Illawarra South Coast",
      "Jobactive caseload ; Refugee ; Inner Metropolitan Melbourne",
      "Jobactive caseload ; Refugee ; Kalgoorlie",
      "Jobactive caseload ; Refugee ; Mackay",
      "Jobactive caseload ; Refugee ; Mid North Coast",
      "Jobactive caseload ; Refugee ; Mid North SA",
      "Jobactive caseload ; Refugee ; Murray and South East",
      "Jobactive caseload ; Refugee ; Murray Riverina",
      "Jobactive caseload ; Refugee ; New England and North West",
      "Jobactive caseload ; Refugee ; Norfolk Island",
      "Jobactive caseload ; Refugee ; North and North Western Tasmania",
      "Jobactive caseload ; Refugee ; North Coast",
      "Jobactive caseload ; Refugee ; North Eastern Melbourne",
      "Jobactive caseload ; Refugee ; North West Country SA",
      "Jobactive caseload ; Refugee ; North Western Melbourne",
      "Jobactive caseload ; Refugee ; Perth - North",
      "Jobactive caseload ; Refugee ; Perth - South",
      "Jobactive caseload ; Refugee ; Somerset",
      "Jobactive caseload ; Refugee ; South Coast of Victoria",
      "Jobactive caseload ; Refugee ; South Eastern Melbourne and Peninsula",
      "Jobactive caseload ; Refugee ; South West WA",
      "Jobactive caseload ; Refugee ; Sydney East Metro",
      "Jobactive caseload ; Refugee ; Sydney Greater West",
      "Jobactive caseload ; Refugee ; Sydney North and West",
      "Jobactive caseload ; Refugee ; Sydney South West",
      "Jobactive caseload ; Refugee ; Townsville (includes Mt Isa)",
      "Jobactive caseload ; Refugee ; Western Melbourne",
      "Jobactive caseload ; Refugee ; Wide Bay and Sunshine Coast",
      "Jobactive caseload ; Refugee ; Wimmera Mallee",
      "Jobactive caseload ; Refugee ; Wivenhoe",
      "Jobactive caseload ; Refugee ; Online Employment Services Trial",
      "Jobactive caseload ; Refugee ; Employment Region Unknown"
    )
  )
})
